TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: SLOWFAST_32x2_R101_50_50.pkl
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: True
  CHECKPOINT_EPOCH_RESET : True

DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]

DETECTION:
  ENABLE: True
  ALIGNED: False

AVA:
  BGR: False
  DETECTION_SCORE_THRESH: 0.8

  # ✅ YOUR CUSTOM DATA
  ANNOTATION_DIR: ../data/combined/annotations
  FRAME_DIR: ../data/combined/frames/
  FRAME_LIST_DIR: ../data/combined/annotations
  TRAIN_LISTS: ['combined_train_frames.csv']
  TRAIN_GT_BOX_LISTS: ['combined_train_labels.csv']
  TRAIN_PREDICT_BOX_LISTS: []
  TEST_LISTS: ['combined_val_frames.csv']
  TEST_PREDICT_BOX_LISTS: ['combined_val_labels.csv']
  GROUNDTRUTH_FILE: combined_val_labels.csv
  LABEL_MAP_FILE: action_labels.pbtxt
  EXCLUSION_FILE: excluded.csv

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5

RESNET:
  DEPTH: 101
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  ZERO_INIT_FINAL_BN: True
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]

NONLOCAL:
  LOCATION: [[[], []], [[], []], [[6, 13, 20], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]

BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.01
  BASE_LR_SCALE_NUM_SHARDS: False
  BETAS: (0.9, 0.999)
  CLIP_GRAD_L2NORM: None
  CLIP_GRAD_VAL: None
  COSINE_AFTER_WARMUP: False
  COSINE_END_LR: 0.0
  DAMPENING: 0.0
  GAMMA: 0.1
  LARS_ON: False
  LAYER_DECAY: 1.0
  LRS: []
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  NESTEROV: True
  OPTIMIZING_METHOD: sgd
  STEPS: []
  STEP_SIZE: 1
  WARMUP_EPOCHS: 0.0
  WARMUP_FACTOR: 0.1
  WARMUP_START_LR: 0.01
  WEIGHT_DECAY: 1e-07
  ZERO_WD_1D_PARAM: False

# SOLVER:
#   BASE_LR: 0.001                     # Lower base LR for fine-tuning pretrained backbone
#   BASE_LR_SCALE_NUM_SHARDS: False
#   BETAS: (0.9, 0.999)
#   CLIP_GRAD_L2NORM: 1.0              # Enable gradient clipping (optional for stability)
#   CLIP_GRAD_VAL: None
#   COSINE_AFTER_WARMUP: True          # Cosine decay after warmup
#   COSINE_END_LR: 0.00001             # Final LR close to zero
#   DAMPENING: 0.0
#   GAMMA: 0.1
#   LARS_ON: False
#   LAYER_DECAY: 1.0
#   LRS: []
#   LR_POLICY: cosine
#   MAX_EPOCH: 50
#   MOMENTUM: 0.9
#   NESTEROV: True
#   OPTIMIZING_METHOD: sgd
#   STEPS: []                          # Not using step LR since cosine is enabled
#   STEP_SIZE: 1
#   WARMUP_EPOCHS: 5.0                   # Gradual warmup for stable start
#   WARMUP_FACTOR: 0.1
#   WARMUP_START_LR: 0.0001            # Very small warmup LR
#   WEIGHT_DECAY: 1e-4                 # Slightly higher for regularization
#   ZERO_WD_1D_PARAM: False

MODEL:
  NUM_CLASSES: 9  # ✅ CHANGED from 80 to 9
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid

TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 1

DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
